# -*- coding: utf-8 -*-
import cv2 as cv
import matplotlib.pyplot as plt

plt.figure(1)
img1 = cv.imread('../../ImageMaterial/DIP3/Fig0316(1)(top_left).tif', cv.IMREAD_COLOR)
plt.subplot(2, 4, 1)
plt.imshow(img1, cmap='Greys_r')
plt.xticks([])
plt.yticks([])
plt.subplot(2, 4, 5)
plt.hist(img1.ravel(), bins='auto', range=[0, 256], density=True)
plt.xticks([])
plt.yticks([])
plt.tight_layout()

img2 = cv.imread('../../ImageMaterial/DIP3/Fig0316(2)(2nd_from_top).tif', cv.IMREAD_COLOR)
plt.subplot(2, 4, 2)
plt.imshow(img2, cmap='Greys_r')
plt.xticks([])
plt.yticks([])
plt.subplot(2, 4, 6)
plt.hist(img2.ravel(), bins='auto', range=[0, 256], density=True)
plt.xticks([])
plt.yticks([])
plt.tight_layout()

img3 = cv.imread('../../ImageMaterial/DIP3/Fig0316(3)(third_from_top).tif', cv.IMREAD_COLOR)
plt.subplot(2, 4, 3)
plt.imshow(img3, cmap='Greys_r')
plt.xticks([])
plt.yticks([])
plt.subplot(2, 4, 7)
plt.hist(img3.ravel(), bins='auto', range=[0, 256], density=True)
plt.xticks([])
plt.yticks([])
plt.tight_layout()

img4 = cv.imread('../../ImageMaterial/DIP3/Fig0316(4)(bottom_left).tif', cv.IMREAD_COLOR)
plt.subplot(2, 4, 4)
plt.imshow(img4, cmap='Greys_r')
plt.xticks([])
plt.yticks([])
plt.subplot(2, 4, 8)
plt.hist(img4.ravel(), bins='auto', range=[0, 256], density=True)
plt.xticks([])
plt.yticks([])
plt.tight_layout()

plt.show()

plt.figure(2)
plt.subplot(3, 4, 1)
plt.imshow(img1, cmap='Greys_r')
plt.xticks([]), plt.yticks([])
imgE1 = cv.equalizeHist(cv.cvtColor(img1, code=cv.COLOR_BGR2GRAY))
plt.subplot(3, 4, 5)
plt.imshow(imgE1, cmap='Greys_r')
plt.xticks([]), plt.yticks([])
plt.subplot(3, 4, 9)
plt.hist(imgE1.ravel(), bins='auto', range=[0, 256], density=True)
plt.xticks([]), plt.yticks([])
plt.tight_layout()

plt.subplot(3, 4, 2)
plt.imshow(img2, cmap='Greys_r')
plt.xticks([]), plt.yticks([])
imgE2 = cv.equalizeHist(cv.cvtColor(img2, code=cv.COLOR_BGR2GRAY))
plt.subplot(3, 4, 6)
plt.imshow(imgE2, cmap='Greys_r')
plt.xticks([]), plt.yticks([])
plt.subplot(3, 4, 10)
plt.hist(imgE2.ravel(), bins='auto', range=[0, 256], density=True)
plt.xticks([]), plt.yticks([])
plt.tight_layout()

plt.subplot(3, 4, 3)
plt.imshow(img3, cmap='Greys_r')
plt.xticks([]), plt.yticks([])
imgE3 = cv.equalizeHist(cv.cvtColor(img3, code=cv.COLOR_BGR2GRAY))
plt.subplot(3, 4, 7)
plt.imshow(imgE3, cmap='Greys_r')
plt.xticks([]), plt.yticks([])
plt.subplot(3, 4, 11)
plt.hist(imgE3.ravel(), bins='auto', range=[0, 256], density=True)
plt.xticks([]), plt.yticks([])
plt.tight_layout()

plt.subplot(3, 4, 4)
plt.imshow(img4, cmap='Greys_r')
plt.xticks([]), plt.yticks([])
imgE4 = cv.equalizeHist(cv.cvtColor(img4, code=cv.COLOR_BGR2GRAY))
plt.subplot(3, 4, 8)
plt.imshow(imgE4, cmap='Greys_r')
plt.xticks([]), plt.yticks([])
plt.subplot(3, 4, 12)
plt.hist(imgE4.ravel(), bins='auto', range=[0, 256], density=True)
plt.xticks([]), plt.yticks([])
plt.tight_layout()
# plt.suptitle('histogram equalization')
plt.show()
